name: covclang
on:
  push:
jobs:
  test-coverage:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out this repository
        uses: actions/checkout@v4.1.0

      - name: Install llvm
        run: sudo apt install llvm

      - name: Build and test this project
        run: sh coverage-clang.sh
